name: Cross-Platform Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Record Start Time
        run: |
          echo "Run Start Time: $(date)" >> run_info.log
          echo "Runner OS: ${{ matrix.os }}" >> run_info.log

      - name: Run target Milvus
        run: |
          docker pull milvusdb/milvus:master-latest

      - name: Record End Time
        run: |
          echo "Run End Time: $(date)" >> run_info.log

      - name: Display Log
        run: cat run_info.log

      - name: Commit Log File
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add run_info.log
          git commit -m "Add run_info.log"
          git push
        if: github.ref == 'refs/heads/main'
